# Some performance results

Here are a few informal results for computing principal components over
variants for 2,504 whole genomes from the NIH using the code and notes from:

- http://bwlewis.github.io/1000_genomes_examples/PCA_overview.html
- http://bwlewis.github.io/1000_genomes_examples/notes.html
- http://bwlewis.github.io/1000_genomes_examples/PCA_whole_genome.html


Wall-clock times for each of two phases, data parsing and PCA computation, are
reported below. I collected these results over a long time (over a year), and
with slightly different versions of the underlying code as I developed it. So
take these results with a grain of salt please.


## My desktop PC (file-based pca-mpi.R)

System configuration was

- CPU: Single AMD A10-7850K APU 3.7 GHz (four physical CPU cores)
- RAM: 16 GB Non-ECC Synchronous Unbuffered RAM 1,600 MHz
- SSD: PCI Express OCZ-REVODRIVE3 X2, 960 GB
- OS: Ubuntu 15.10 (Linux kernel 4.2.0-16)
- R version 3.2.3 (2015-12-10)
- OpenBLAS library version 0.2.14-1ubuntu1 (based on Goto's BLAS version 1.13), `OMP_NUM_THREADS=1`,
- working directory: SSD
- R SMP cores:  4
- Single MPI node
- submatrix chunk size: 1e8  (max nonzero elements)

Data parsing time: 9,970 seconds.
PCA time:  6,480 seconds (about 2 hours).


## Amazon r3.8xlarge (file-based, pca-mpi.R)

System configuration was

- CPU: 2 x Intel Xeon E5-2670 v2 @ 2.49 GHz (16 cores, 32 threads)
- RAM: 244 GB
- OS: Ubuntu 14.10
- R version 3.3.1
- OpenBLAS and OMP_NUM_THREADS=1
- R SMP cores: 16
- Single MPI node
- /dev/shm expanded to full RAM size tmpfs mount
- working directory /dev/shm
- submatrix chunk size: 1e8  (max nonzero elements)

Data parsing time: 2,400 seconds.
PCA time: 521 seconds.


## Amazon r4.16xlarge (in memory, pca-smp.R)

System configuration

- CPU: 4 x Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (32 cores, 64 threads)
- RAM: 488 GB
- OS: Ubuntu 14.10
- R version 3.3.3
- OpenBLAS and OMP_NUM_THREADS=1
- R SMP cores: **64** _NOTE: ACCIDENTALLY OVERCOMMITTED CPU HERE_
- /dev/shm expanded to full RAM size tmpfs mount
- working directory /dev/shm
- submatrix chunk size: 1e8  (max nonzero elements)

Data parsing time: 2,444 seconds.
PCA time: 839 seconds.

**NOTE** I accidentally used too may cores here, which I think ruined the
performance. At some point, I will re-run this test and add a new result below
with the correct core count.


## HP ProLiant DL580 G7 (in memory, pca-smp.R)

System configuration

- CPU: 4 x Intel(R) Xeon(R) CPU E7- 4870  @ 2.40GHz (40 cores, 80 threads)
- RAM: 1 TB
- OS: RHEL 7.1
- R version 3.3.3
- OpenBLAS and OMP_NUM_THREADS=1
- R SMP cores: 40
- working directory /dev/shm
- submatrix chunk size: 1e8  (max nonzero elements)

Data parsing time: 3035 seconds.
PCA time: 971 seconds.
